# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
# parameters:
#   - name: LoopList
#     type: object
#     default: $[ 5 ]



pool:
  vmImage: 'windows-latest'

variables:
  - name: SomeNumber
    value: 5
  - name: SomeList

steps:
- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      import sys
      with open('temp.txt', 'w') as fp:
        for i in range(int(sys.argv[1])):
          fp.write(f'{i},')
        fp.write(f'{i})
      with open('temp.bat', 'w') as bat:
        bat.write("set /p TestVal=< temp.txt")
    arguments: '$(SomeNumber)'
- task: BatchScript@1
  inputs:
    filename: 'temp.bat'
    modifyEnvironment: true
- template: azure_template.yaml
  parameters:
    param: [$(TestVal)]
